version: "3"
services:
  crawler:
    build: .
    environment:
      - DRIVER_PATH=/path/to/driver
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    depends_on:
      - redis
    volumes:
      - ./linkedin_crawler:/app
  redis:
    image: redis
    ports:
      - "6379:6379"
